In [5]:
import pandas as pd

df=pd.read_csv("C:\\Users\\Dell\\Downloads\\messy_customer_loan_dataset.csv")
df

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,477723.0,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,65.0,1394481.0,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,45.0,543340.0,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [ ]:
# Basic Cleaning

In [6]:
#1.Load the CSV file using Pandas and display the first 10 rows.
df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
5,CUST100925,32.0,317590.0,690.0,Salaried,Graduate,M,Mumbai,Premium,Auto,235549.0,120,5.0,0.46,No
6,CUST100758,39.0,322966.0,707.0,Contract,Graduate,Married,Chennai,Mass,Personal,563319.0,24,7.0,0.323,No
7,CUST100793,54.0,999108.0,689.0,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783.0,48,NaN,0.233,Yes
8,CUST100965,65.0,478191.0,758.0,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872.0,72,5.0,0.375,No
9,CUST101198,67.0,1063307.0,774.0,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693.0,120,2.0,0.394,Yes

In [7]:
#2.Display the number of rows and columns in the dataset.
df.shape                                                    #row and columns

(1535, 15)

In [13]:
#3.Display all column names and identify which column names have
#leading/trailing spaces.

# Display all column names
print(df.columns.tolist())

# Identify columns with leading/trailing spaces
for col in df.columns:
    if col != col.strip():
        print(repr(col))

[' Customer ID ', 'Age ', 'Annual Income', 'credit Score ', 'Employment-Type', 'Education  Level', 'marital_status', 'city', 'customer_segment ', 'loan_type', 'Loan Amount (INR)', 'tenure Months', 'Monthly Visits ', 'debt_to_income', 'Loan Approved?']
' Customer ID '
'Age '
'credit Score '
'customer_segment '
'Monthly Visits '

In [15]:
#4.Clean all column names by removing extra spaces and converting them into a
#consistent format such as snake_case.

# Clean column names
df.columns = (
    df.columns
    .str.strip()                    # Remove leading/trailing spaces
    .str.lower()                    # Convert to lowercase
    .str.replace(" ", "_")          # Replace spaces with _
    .str.replace(r"[^a-z0-9_]", "", regex=True)  # Remove special characters
)

# Display cleaned column names
df.columns.tolist()

['customer_id',
 'age',
 'annual_income',
 'credit_score',
 'employmenttype',
 'education__level',
 'marital_status',
 'city',
 'customer_segment',
 'loan_type',
 'loan_amount_inr',
 'tenure_months',
 'monthly_visits',
 'debt_to_income',
 'loan_approved']

In [17]:
#5.Check the data type of every column.
df.dtypes

customer_id         object
age                 object
annual_income       object
credit_score        object
employmenttype      object
education__level    object
marital_status      object
city                object
customer_segment    object
loan_type           object
loan_amount_inr     object
tenure_months        int64
monthly_visits      object
debt_to_income      object
loan_approved       object
dtype: object

In [18]:
#6.Find the total number of missing values in each column.

df.isnull().sum()

customer_id           0
age                  71
annual_income        84
credit_score         77
employmenttype       60
education__level     46
marital_status        0
city                 52
customer_segment      0
loan_type             0
loan_amount_inr     102
tenure_months         0
monthly_visits       55
debt_to_income       89
loan_approved         0
dtype: int64

In [20]:
#7.Find the percentage of missing values in each column.

df.isnull().sum() / len(df) * 100

customer_id         0.000000
age                 4.625407
annual_income       5.472313
credit_score        5.016287
employmenttype      3.908795
education__level    2.996743
marital_status      0.000000
city                3.387622
customer_segment    0.000000
loan_type           0.000000
loan_amount_inr     6.644951
tenure_months       0.000000
monthly_visits      3.583062
debt_to_income      5.798046
loan_approved       0.000000
dtype: float64

In [21]:
#8.Find all rows where Age is missing.

# Find rows where Age is missing
missing_age = df[df["age"].isnull()]
missing_age

,customer_id,age,annual_income,credit_score,employmenttype,education__level,marital_status,city,customer_segment,loan_type,loan_amount_inr,tenure_months,monthly_visits,debt_to_income,loan_approved
21,CUST100354,NaN,302606.0,726.0,NaN,Graduate,Single,Bengaluru,Mass,Auto,269320.0,84,6.0,0.353,No
29,CUST100989,NaN,650000 INR,778.0,Self-Employed,Graduate,Divorced,Pune,unknown,Home,1083921.0,48,5.0,0.4x,No
100,CUST101150,NaN,100,723.0,Self-Employed,12th,Married,NaN,Mass,Education,454937.0,48,five,0.303,Yes
108,CUST100535,NaN,458878.0,782.0,Salaried,Diploma,Married,Mumbai,Mass,Auto,549385.0,36,7.0,0.279,No
113,CUST101055,NaN,1112464.0,120,Salaried,Diploma,Married,Kolkata,Mass,Auto,427759.0,84,3.0,0.102,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,CUST100392,NaN,570532.0,766.0,Contract,Postgraduate,Married,Jaipur,Mass,Home,937612.0,36,3.0,0.51,Yes
1430,CUST101368,NaN,519228.0,728.0,Business,Postgraduate,Married,Hyderabad,Mass,Home,514679.0,12,4.0,0.392,Yes
1498,CUST100700,NaN,658802.0,772.0,Contract,Postgraduate,Married,Mumbai,Mass,Auto,257699.0,24,4.0,0.584,Yes
1503,CUST100748,NaN,338339.0,673.0,Business,Graduate,Married,Chennai,Premium,Business,223704.0,12,7.0,0.02,No
1516,CUST100770,NaN,708229.0,801.0,Business,NaN,Single,Chennai,Premium,Personal,341664.0,120,5.0,0.651,Yes

In [23]:
#9.Find all rows where Annual Income is missing.

# Find rows where Annual Income is missing
missing_income = df[df["annual_income"].isnull()]
missing_income

,customer_id,age,annual_income,credit_score,employmenttype,education__level,marital_status,city,customer_segment,loan_type,loan_amount_inr,tenure_months,monthly_visits,debt_to_income,loan_approved
41,CUST101081,64.0,NaN,749.0,Self-Employed,Diploma,Single,Kolkata,Premium,Personal,254754.0,24,5.0,0.327,No
103,CUST101403,35.0,NaN,660.0,Self-Employed,Graduate,Married,Delhi,Affluent,Home,NaN,36,4.0,0.402,No
119,CUST101095,36.0,NaN,782.0,self-employed,Postgraduate,Married,Bengaluru,Affluent,Home,225725.0,60,5.0,0.341,Yes
132,CUST101048,49.0,NaN,713.0,Salaried,Postgraduate,Single,Bengaluru,Affluent,auto,301697.0,48,7.0,0.35,Yes
144,CUST100530,64.0,NaN,761.0,Business,Diploma,Single,NaN,Affluent,Business,1182185.0,120,7.0,0.02,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,CUST100776,65.0,NaN,667.0,Self-Employed,GRADUATE,Single,Mumbai,Mass,Personal,995167.0,72,3.0,0.6,Yes
1493,CUST101496,41.0,NaN,662.0,Self-Employed,12th,Single,Kolkata,Affluent,Education,693422.0,48,5.0,0.272,No
1501,CUST100475,50.0,NaN,802.0,Contract,12th,Divorced,Kolkata,Mass,Personal,1488587.0,36,5.0,0.023,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [24]:
#10.Remove completely duplicate rows and report how many duplicate rows were
#removed.

# Count duplicate rows before removing
duplicate_count = df.duplicated().sum()

# Remove completely duplicate rows
df = df.drop_duplicates()

# Report number of duplicates removed
print("Duplicate rows removed:", duplicate_count)

Duplicate rows removed: 35

In [ ]:
# Data Type & Invalid Values

In [28]:
#11.The Age column contains numbers as well as values like "unknown" and
#"twenty five". Clean this column and convert it into a proper numeric column.

import pandas as pd

# Create a copy of the DataFrame
df = df.copy()

# Convert Age to numeric
df["age"] = pd.to_numeric(df["age"], errors="coerce")

# Display the cleaned Age column
df["age"].head()

# Check data type
df["age"].dtype

dtype('float64')

In [31]:
#12.The Annual Income column contains values such as 650000 INR, ₹720000,
#1.2L, and N/A. Clean the column and convert the valid values into numeric
#format.

import pandas as pd
import numpy as np

def clean_income(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()

    # Missing values
    if value in ["n/a", "na", "nan", "unknown", ""]:
        return np.nan

    # Remove INR and  symbols
    value = value.replace("inr", "")
    value = value.replace("₹", "")
    value = value.replace(",", "").strip()

    # Convert Lakh values
    if value.endswith("l"):
        return float(value[:-1]) * 100000

    # Convert normal numeric values
    return pd.to_numeric(value, errors="coerce")


# Clean Annual Income
df["annual_income"] = df["annual_income"].apply(clean_income)

# Check results
print(df["annual_income"].head(10))

# Check data type
print("Data type:", df["annual_income"].dtype)

0     297809.0
1    1048283.0
2    1043481.0
3     369591.0
4     666989.0
5     317590.0
6     322966.0
7     999108.0
8     478191.0
9    1063307.0
Name: annual_income, dtype: float64
Data type: float64

In [32]:
#13.Clean the Credit Score column and identify values that cannot be converted
#into numbers.

import pandas as pd

# Identify values that cannot be converted into numbers
invalid_credit_scores = df[
    pd.to_numeric(df["credit_score"], errors="coerce").isna()
    & df["credit_score"].notna()
]

print("Invalid Credit Score values:")
print(invalid_credit_scores["credit_score"].unique())

# Clean Credit Score column
df["credit_score"] = pd.to_numeric(
    df["credit_score"],
    errors="coerce"
)

# Check data type
print("Data type:", df["credit_score"].dtype)

Invalid Credit Score values:
['unknown' 'seven hundred' '720 points']
Data type: float64

In [4]:
#14.The Loan Amount column contains currency symbols, text, and numeric
#values. Remove the unwanted characters and convert it into numeric format.

import pandas as pd
df=pd.read_csv("C:\\Users\\Dell\\Downloads\\messy_customer_loan_dataset.csv")


df.columns = df.columns.str.strip()

df['Loan Amount (INR)'] = pd.to_numeric(
    df['Loan Amount (INR)']
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True),
    errors='coerce'
)

print(df['Loan Amount (INR)'])

0         378342.0
1         751792.0
2         892792.0
3         908250.0
4         386370.0
           ...
1530     1106455.0
1531      222828.0
1532    50000000.0
1533      302389.0
1534      753995.0
Name: Loan Amount (INR), Length: 1535, dtype: float64

In [3]:
print(df.columns)                                              #dataset present columns check

Index([' Customer ID ', 'Age ', 'Annual Income', 'credit Score ',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment ', 'loan_type', 'Loan Amount (INR)', 'tenure Months',
       'Monthly Visits ', 'debt_to_income', 'Loan Approved?'],
      dtype='object')

In [5]:
#15.The Monthly Visits column contains values such as "five", "N/A", and "-".
#Convert valid values into numeric values and handle invalid values.


import pandas as pd

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Convert valid numeric values
df['Monthly Visits'] = pd.to_numeric(
    df['Monthly Visits'],
    errors='coerce'
)

# Check the result
print(df['Monthly Visits'])

0        3.0
1       11.0
2        4.0
3       10.0
4        4.0
        ...
1530     NaN
1531     8.0
1532     9.0
1533     9.0
1534     5.0
Name: Monthly Visits, Length: 1535, dtype: float64

In [7]:
#16.Clean the Debt to Income column where some values are written like 35%
#and 0.4x. Convert the valid values into a consistent numeric format.


import pandas as pd

# Clean Debt to Income column
df['debt_to_income'] = (
    df['debt_to_income']
    .astype(str)
    .str.strip()
    .str.replace('%', '', regex=False)
    .str.replace('x', '', regex=False)
)

# Convert to numeric
df['debt_to_income'] = pd.to_numeric(
    df['debt_to_income'],
    errors='coerce'
)

# Convert percentage values to decimal
df.loc[df['debt_to_income'] > 1, 'debt_to_income'] = (
    df.loc[df['debt_to_income'] > 1, 'debt_to_income'] / 100
)

df['debt_to_income']

0       0.258
1       0.558
2         NaN
3       0.356
4       0.169
        ...
1530    0.569
1531    0.344
1532    0.084
1533    0.089
1534    0.259
Name: debt_to_income, Length: 1535, dtype: float64

In [9]:
#17.After cleaning the numerical columns, check which columns are still stored as
#object data type.

# Check data types of all columns
print(df.dtypes)

# Show only columns with object data type
object_columns = df.select_dtypes(include='object').columns
object_columns

Customer ID           object
Age                   object
Annual Income         object
credit Score          object
Employment-Type       object
Education  Level      object
marital_status        object
city                  object
customer_segment      object
loan_type             object
Loan Amount (INR)    float64
tenure Months          int64
Monthly Visits       float64
debt_to_income       float64
Loan Approved?        object
dtype: object

Index(['Customer ID', 'Age', 'Annual Income', 'credit Score',
       'Employment-Type', 'Education  Level', 'marital_status', 'city',
       'customer_segment', 'loan_type', 'Loan Approved?'],
      dtype='object')

In [ ]:
#Categorical Cleaning

In [11]:
#18.Find all unique values in the Employment-Type column.

# Find all unique values in Employment-Type
unique_values = df['Employment-Type'].unique()
unique_values

array(['Self-Employed', 'Contract', 'Salaried', ' SALARIED ',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

In [13]:
#19.Standardize the Employment-Type column so that values such as salaried,
#SALARIED, and Salaried become one consistent value.

# Remove extra spaces and standardize capitalization
df['Employment-Type'] = (
    df['Employment-Type']
    .astype(str)
    .str.strip()
    .str.title()
)

# Check unique values
df['Employment-Type'].unique()

array(['Self-Employed', 'Contract', 'Salaried', 'Self Employed',
       'Business', 'Nan', 'Unknown'], dtype=object)

In [15]:
#20.Clean the Education Level column and make values such as graduate,
#GRADUATE, and Graduate consistent.

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Standardize Education Level values
df['Education  Level'] = (
    df['Education  Level']
    .astype(str)
    .str.strip()
    .str.title()
)

# Check unique values
df['Education  Level'].unique()

array(['12Th', 'Graduate', 'Postgraduate', 'Diploma', 'Nan',
       'Post Graduate', 'Other'], dtype=object)

In [17]:
#21.Clean the City column. Identify incorrect or inconsistent values such as
#hyderbad, Hyd, Bangalore, and Bengaluru.

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Clean and standardize City values
df['city'] = (
    df['city']
    .astype(str)
    .str.strip()
    .str.lower()
)

# Replace incorrect/inconsistent values
df['city'] = df['city'].replace({
    'hyderbad': 'Hyderabad',
    'hyd': 'Hyderabad',
    'hyderabad': 'Hyderabad',
    'bangalore': 'Bengaluru',
    'bengaluru': 'Bengaluru'
})

# Check unique values
df['city'].unique()

array(['mumbai', 'jaipur', 'kolkata', 'Hyderabad', 'chennai', 'Bengaluru',
       'nan', 'delhi', 'pune'], dtype=object)

In [19]:
#22.Find all unique values in the Customer Segment column and identify invalid
#categories.

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Find all unique values
df['customer_segment'].unique()

array(['Mass', ' PREMIUM', 'Affluent', 'Premium', 'SME', 'premium ',
       'unknown', 'High Value', 'mass'], dtype=object)

In [21]:
#23.Clean the Loan Type column so that values such as personal, PERSONAL,
#and personal loan are standardized.

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Clean Loan Type
df['loan_type'] = (
    df['loan_type']
    .astype(str)
    .str.strip()
    .str.lower()
)

# Standardize values
df['loan_type'] = df['loan_type'].replace({
    'personal': 'Personal Loan',
    'personal loan': 'Personal Loan'
})

# Check unique values
df['loan_type'].unique()

array(['education', 'auto', 'home', 'Personal Loan', 'business',
       'home loan', 'unknown'], dtype=object)

In [23]:
#24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No,
#NO, N, and 0. Convert them into only Yes/No.

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Standardize Loan Approved values
df['Loan Approved?'] = (
    df['Loan Approved?']
    .astype(str)
    .str.strip()
    .str.lower()
)

# Convert values to Yes/No
df['Loan Approved?'] = df['Loan Approved?'].replace({
    'yes': 'Yes',
    'y': 'Yes',
    '1': 'Yes',
    'no': 'No',
    'n': 'No',
    '0': 'No'
})

# Check unique values
df['Loan Approved?'].unique()

array(['No', 'Yes', 'pending', 'approved'], dtype=object)

In [ ]:
#Outliers & Data Validation

In [26]:
#25.Check the Age column and identify unrealistic ages such as negative ages or
#ages above 100.

import pandas as pd

# Convert Age to numeric
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

# Identify unrealistic ages
unrealistic_ages = df[
    (df['Age'] < 0) | (df['Age'] > 100)
]

unrealistic_ages

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
143,CUST101478,105.0,654405.0,705.0,Self-Employed,Other,Single,pune,Affluent,business,307579.0,12,9.0,0.398,Yes
264,CUST100715,105.0,728296.0,668.0,Salaried,12Th,Married,jaipur,SME,Personal Loan,317698.0,48,4.0,0.186,Yes
308,CUST100846,105.0,479269.0,715.0,Self-Employed,Graduate,Married,pune,Affluent,home,1894157.0,60,1.0,0.380,Yes
383,CUST101107,-3.0,982428.0,NaN,Business,Graduate,Married,mumbai,SME,auto,NaN,72,1.0,0.249,Yes
581,CUST100261,130.0,811910.0,828.0,Self-Employed,Nan,Married,chennai,Affluent,Personal Loan,493393.0,60,4.0,0.426,Yes
689,CUST100639,-3.0,533794.0,694.0,Salaried,Graduate,Single,Hyderabad,Affluent,home,NaN,120,6.0,0.256,Yes
892,CUST101177,-3.0,25000000,659.0,Business,Nan,Single,delhi,Affluent,auto,623885.0,120,5.0,0.257,Yes
923,CUST100556,105.0,657328.0,878.0,Business,Diploma,Married,mumbai,High Value,education,694953.0,24,3.0,0.261,Yes
1039,CUST101156,-3.0,270249.0,677.0,Contract,Other,Married,chennai,Mass,education,220207.0,120,6.0,NaN,No
1070,CUST100849,-3.0,NaN,844.0,Business,Diploma,Married,Bengaluru,Premium,business,3599535.0,48,8.0,0.639,Yes
1399,CUST101411,105.0,681307.0,760.0,Contract,Graduate,Single,kolkata,Mass,home,237072.0,36,5.0,0.298,Yes
1465,CUST101105,105.0,426130.0,771.0,Business,Graduate,Married,chennai,Mass,business,261086.0,72,2.0,NaN,Yes

In [28]:
#26.Check the Credit Score column and identify values outside the valid credit-
#score range.


import pandas as pd

# Convert Credit Score to numeric
df['credit Score'] = pd.to_numeric(
    df['credit Score'],
    errors='coerce'
)

# Identify invalid credit scores
invalid_scores = df[
    (df['credit Score'] < 300) |
    (df['credit Score'] > 850)
]

invalid_scores

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,jaipur,PREMIUM,auto,751792.0,48,11.0,0.558,Yes
57,CUST100276,43.0,769913.0,852.0,Salaried,Diploma,Married,Bengaluru,Affluent,home,363928.0,120,10.0,0.291,No
83,CUST100068,38.0,589676.0,856.0,Business,Graduate,Single,chennai,Affluent,auto,162497.0,72,5.0,0.645,pending
97,CUST100644,43.0,983121.0,905.0,Contract,Graduate,Single,jaipur,Mass,Personal Loan,463446.0,120,4.0,0.177,Yes
113,CUST101055,NaN,1112464.0,120.0,Salaried,Diploma,Married,kolkata,Mass,auto,427759.0,84,3.0,0.102,No
123,CUST101109,65.0,426853.0,999.0,Contract,Diploma,Married,delhi,Affluent,Personal Loan,259649.0,12,10.0,0.334,Yes
126,CUST100276,43.0,769913.0,852.0,Salaried,Diploma,Married,Bengaluru,Affluent,home,363928.0,120,10.0,0.291,No
178,CUST100999,66.0,869564.0,854.0,Self-Employed,12Th,Married,Hyderabad,Affluent,Personal Loan,623296.0,84,3.0,0.157,approved
295,CUST101220,41.0,442392.0,250.0,Business,Diploma,Married,delhi,Affluent,auto,50000000.0,72,9.0,0.275,Yes
296,CUST100745,58.0,1044693.0,0.0,Business,Postgraduate,Married,Bengaluru,Affluent,auto,NaN,36,3.0,0.261,No
327,CUST100351,46.0,NaN,856.0,Salaried,Graduate,Single,Bengaluru,Affluent,home,91808.0,12,5.0,0.581,Yes
342,CUST100255,52.0,402265.0,120.0,Business,Diploma,Married,nan,Mass,home,NaN,36,9.0,0.376,Yes
361,CUST100760,55.0,1474069.0,858.0,Nan,Graduate,Married,Bengaluru,Mass,auto,367688.0,12,5.0,0.404,Yes
369,CUST101205,51.0,633034.0,889.0,Contract,12Th,Married,Hyderabad,Mass,auto,654316.0,24,4.0,0.180,Yes
399,CUST100430,54.0,1065784.0,863.0,Salaried,Postgraduate,Single,Hyderabad,Affluent,home loan,530332.0,72,4.0,0.178,Yes
542,CUST100909,38.0,778215.0,120.0,Business,12Th,Married,mumbai,Affluent,Personal Loan,997263.0,48,2.0,NaN,Yes
680,CUST100666,53.0,680059.0,120.0,Contract,Graduate,Married,delhi,Premium,Personal Loan,116706.0,72,1.0,0.512,No
690,CUST100778,26.0,374253.0,860.0,Business,Graduate,Married,chennai,Mass,business,344600.0,12,6.0,0.489,No
710,CUST100046,66.0,276121.0,0.0,Business,Other,unknown,chennai,Premium,auto,877671.0,48,1.0,0.263,Yes
726,CUST100922,47.0,827522.0,903.0,Salaried,Postgraduate,Married,delhi,Premium,home,355150.0,120,3.0,0.207,Yes
807,CUST100937,28.0,783241.0,120.0,Contract,Graduate,Married,kolkata,Mass,home,266100.0,120,NaN,0.112,Yes
830,CUST100610,61.0,unknown,870.0,Contract,Graduate,Married,Hyderabad,Affluent,home,363432.0,12,6.0,0.475,No
867,CUST100145,67.0,465955.0,872.0,Contract,Postgraduate,Married,pune,Mass,home,529361.0,12,2.0,0.483,Yes
923,CUST100556,105.0,657328.0,878.0,Business,Diploma,Married,mumbai,High Value,education,694953.0,24,3.0,0.261,Yes
927,CUST100824,51.0,618064.0,250.0,Contract,Graduate,Single,Hyderabad,Mass,Personal Loan,183673.0,12,2.0,0.335,No
930,CUST100508,32.0,NaN,0.0,Contract,12Th,Single,Bengaluru,SME,business,525860.0,24,3.0,NaN,Yes
959,CUST100876,44.0,807700.0,0.0,Business,Postgraduate,Married,Hyderabad,Mass,home,272420.0,60,5.0,0.353,Yes
964,CUST100070,43.0,604540.0,120.0,Salaried,12Th,Single,jaipur,Affluent,home,1603055.0,12,6.0,0.334,No
992,CUST100519,43.0,874545.0,867.0,Business,Graduate,Married,Hyderabad,Premium,Personal Loan,221790.0,84,6.0,0.537,No
1003,CUST100843,63.0,439227.0,868.0,Contract,Graduate,Divorced,pune,Mass,auto,490158.0,48,4.0,0.495,Yes
1068,CUST101469,57.0,1706529.0,878.0,Salaried,12Th,Single,jaipur,Mass,home,154346.0,36,5.0,0.403,Yes
1082,CUST100690,57.0,831564.0,0.0,Business,Postgraduate,Married,mumbai,Premium,business,536613.0,60,5.0,0.534,Yes
1096,CUST101382,NaN,285436.0,865.0,Self-Employed,Postgraduate,Single,Hyderabad,Mass,education,279654.0,60,6.0,0.740,Yes
1114,CUST101376,66.0,947307.0,870.0,Self-Employed,Graduate,Married,jaipur,SME,business,1527137.0,72,6.0,0.386,Yes
1132,CUST100791,25.0,671538.0,861.0,Contract,Diploma,Married,chennai,Mass,home,455260.0,84,7.0,0.317,Yes
1133,CUST100117,22.0,555777.0,887.0,Business,Graduate,Married,kolkata,SME,business,976998.0,24,6.0,0.246,No
1151,CUST100774,54.0,388602.0,863.0,Contract,Nan,Married,nan,Affluent,auto,295354.0,84,5.0,0.382,Yes
1159,CUST100444,43.0,315278.0,250.0,Self-Employed,Graduate,Married,Bengaluru,Affluent,business,700803.0,36,8.0,0.336,No
1217,CUST100302,59.0,NaN,250.0,Contract,Graduate,Married,pune,Mass,Personal Loan,625206.0,84,5.0,0.252,Yes
1229,CUST100644,43.0,983121.0,905.0,Contract,Graduate,Single,jaipur,Mass,Personal Loan,463446.0,120,4.0,0.177,Yes
1232,CUST101284,58.0,733526.0,250.0,Business,Graduate,Married,pune,Affluent,Personal Loan,204868.0,120,6.0,0.449,No
1239,CUST100226,35.0,547979.0,876.0,Self-Employed,12Th,Married,mumbai,Mass,business,346289.0,48,6.0,0.214,Yes
1284,CUST100009,30.0,376040.0,851.0,Contract,Postgraduate,Married,Hyderabad,Affluent,auto,358832.0,24,6.0,0.512,No
1286,CUST101378,56.0,441775.0,120.0,Self-Employed,Graduate,Single,Bengaluru,Mass,business,1153676.0,60,2.0,0.564,Yes
1288,CUST100453,44.0,614537.0,0.0,Salaried,Graduate,Married,jaipur,Mass,business,328075.0,60,4.0,0.377,No
1352,CUST101407,37.0,1874514.0,250.0,Contract,Graduate,Married,mumbai,PREMIUM,Personal Loan,539352.0,12,12.0,0.300,No
1407,CUST100099,50.0,741081.0,854.0,Self-Employed,12Th,Single,delhi,Premium,business,490862.0,12,4.0,0.277,Yes
1461,CUST101414,58.0,759405.0,120.0,Salaried,Nan,Single,jaipur,PREMIUM,auto,366567.0,120,4.0,0.291,Yes
1531,CUST101295,65.0,1394481.0,0.0,Self-Employed,12Th,Single,jaipur,Mass,Personal Loan,222828.0,120,8.0,0.344,Yes

In [29]:
#27.Detect outliers in Annual Income using the IQR method.

import pandas as pd

# Convert Annual Income to numeric
df['Annual Income'] = pd.to_numeric(
    df['Annual Income'],
    errors='coerce'
)

# Calculate Q1 and Q3
Q1 = df['Annual Income'].quantile(0.25)
Q3 = df['Annual Income'].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Calculate lower and upper limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Detect outliers
outliers = df[
    (df['Annual Income'] < lower_limit) |
    (df['Annual Income'] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

print("\nOutliers in Annual Income:")
print(outliers)

Q1: 458701.0
Q3: 871688.75
IQR: 412987.75
Lower Limit: -160780.625
Upper Limit: 1491170.375

Outliers in Annual Income:
     Customer ID   Age  Annual Income  credit Score Employment-Type  \
14    CUST101158  60.0      1548824.0         698.0        Contract
61    CUST100757  55.0      1777657.0         666.0        Contract
74    CUST100238  41.0      1907548.0         678.0        Business
184   CUST100692   NaN      1895511.0         832.0   Self-Employed
208   CUST100616  51.0      1586888.0         708.0        Contract
...          ...   ...            ...           ...             ...
1409  CUST100407  41.0      1521141.0         799.0   Self-Employed
1464  CUST101412  47.0      1996474.0         789.0        Contract
1466  CUST100206  33.0      1604257.0         785.0        Contract
1467  CUST100035  62.0      1531271.0         779.0        Business
1515  CUST100344  45.0     80000000.0         819.0   Self-Employed

     Education  Level marital_status       city customer_segment  \
14           Graduate        Married       pune              SME
61       Postgraduate         Single  Hyderabad          Premium
74           Graduate         Single     mumbai             Mass
184          Graduate        Married     jaipur              SME
208              12Th        Married      delhi             Mass
...               ...            ...        ...              ...
1409         Graduate         Single    kolkata         Affluent
1464     Postgraduate        Married    kolkata       High Value
1466             12Th         Single     mumbai         Affluent
1467     Postgraduate         Single  Hyderabad             mass
1515     Postgraduate         Single     mumbai             Mass

          loan_type  Loan Amount (INR)  tenure Months  Monthly Visits  \
14             home           333121.0             24            10.0
61        education           900253.0             72             3.0
74         business           242378.0             72             0.0
184   Personal Loan           518143.0             48             2.0
208   Personal Loan           461215.0             84             NaN
...             ...                ...            ...             ...
1409           auto           573489.0            120             2.0
1464  Personal Loan           460487.0             72             4.0
1466       business                NaN             24             3.0
1467  Personal Loan           327941.0             24             4.0
1515  Personal Loan           636933.0             12             6.0

      debt_to_income Loan Approved?
14             0.529             No
61             0.304            Yes
74               NaN            Yes
184            0.637             No
208            0.401            Yes
...              ...            ...
1409           0.078            Yes
1464           0.157            Yes
1466           0.355             No
1467           0.179            Yes
1515           0.384            Yes

[63 rows x 15 columns]

In [30]:
#28.Detect outliers in Loan Amount using the IQR method.

import pandas as pd

# Convert Loan Amount to numeric
df['Loan Amount (INR)'] = pd.to_numeric(
    df['Loan Amount (INR)'],
    errors='coerce'
)

# Calculate Q1 and Q3
Q1 = df['Loan Amount (INR)'].quantile(0.25)
Q3 = df['Loan Amount (INR)'].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Calculate limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Detect outliers
outliers = df[
    (df['Loan Amount (INR)'] < lower_limit) |
    (df['Loan Amount (INR)'] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

print("\nOutliers in Loan Amount:")
print(outliers)

Q1: 281541.0
Q3: 691511.0
IQR: 409970.0
Lower Limit: -333414.0
Upper Limit: 1306466.0

Outliers in Loan Amount:
     Customer ID   Age  Annual Income  credit Score Employment-Type  \
11    CUST100679  45.0       856826.0         662.0   Self Employed
25    CUST100071  58.0       454340.0         743.0        Business
58    CUST100345  63.0       477076.0         785.0        Salaried
157   CUST101362  24.0       782709.0         842.0        Salaried
180   CUST100421  64.0      1483255.0         751.0        Contract
...          ...   ...            ...           ...             ...
1406  CUST100684  66.0       513360.0         682.0   Self-Employed
1439  CUST100764  64.0       761542.0         731.0             Nan
1469  CUST100509  33.0       850268.0         829.0        Business
1501  CUST100475  50.0            NaN         802.0        Contract
1532  CUST100861  66.0            NaN         686.0        Contract

     Education  Level marital_status       city customer_segment  \
11       Postgraduate       Divorced        nan         Affluent
25           Graduate         Single     jaipur          Premium
58           Graduate       MARRIED     chennai              SME
157              12Th        Married        nan          Premium
180     Post Graduate        Married  Hyderabad             Mass
...               ...            ...        ...              ...
1406         Graduate        Married     mumbai          Premium
1439         Graduate       MARRIED   Bengaluru             Mass
1469              Nan        Married    kolkata             Mass
1501             12Th       Divorced    kolkata             Mass
1532            Other        Married      delhi             Mass

          loan_type  Loan Amount (INR)  tenure Months  Monthly Visits  \
11        education          1412363.0             12             5.0
25         business          1545154.0             72             3.0
58        education          1575763.0             24             8.0
157   Personal Loan        120000000.0             48             6.0
180            auto          2033263.0             72             3.0
...             ...                ...            ...             ...
1406           auto          1309079.0             60             2.0
1439           auto          2170814.0             72             2.0
1469  Personal Loan          1647932.0             72             4.0
1501  Personal Loan          1488587.0             36             5.0
1532  Personal Loan         50000000.0             36             9.0

      debt_to_income Loan Approved?
11             0.487            Yes
25             0.333            Yes
58             0.419             No
157              NaN             No
180            0.134            Yes
...              ...            ...
1406           0.020            Yes
1439           0.247            Yes
1469           0.329            Yes
1501           0.023            Yes
1532           0.084            Yes

[83 rows x 15 columns]

In [31]:
#29.Check the Debt to Income column and identify impossible values such as
#negative values or values greater than 1.

# Convert Debt to Income to numeric
df['debt_to_income'] = pd.to_numeric(
    df['debt_to_income'],
    errors='coerce'
)

# Identify impossible values
invalid_dti = df[
    (df['debt_to_income'] < 0) |
    (df['debt_to_income'] > 1)
]

print("Impossible Debt to Income values:")
print(invalid_dti)

Impossible Debt to Income values:
     Customer ID   Age  Annual Income  credit Score Employment-Type  \
31    CUST100893  45.0            NaN         815.0   Self-Employed
1425  CUST100593  32.0       470087.0         689.0   Self-Employed
1463  CUST101026  23.0       448155.0         736.0   Self-Employed

     Education  Level marital_status    city customer_segment loan_type  \
31       Postgraduate        Married    pune         Affluent  business
1425         Graduate         Single  jaipur             Mass  business
1463         Graduate        Married  jaipur             Mass      auto

      Loan Amount (INR)  tenure Months  Monthly Visits  debt_to_income  \
31             549241.0             24             4.0            -0.2
1425           263313.0             60             6.0            -0.2
1463           392941.0             72             5.0            -0.2

     Loan Approved?
31               No
1425             No
1463            Yes

In [36]:
#30.Final cleaning task: Create a completely cleaned version of the dataset by:
#• Cleaning column names
#• Removing duplicates
#• Handling missing values
#• Fixing data types
#• Cleaning numerical columns
#• Standardizing categorical values
#• Handling invalid values
#• Detecting and treating outliers
#• Checking the final dataset for remaining errors

import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\Downloads\Task_dataset.csv")

print(df.head())

# ============================================
# 1. LOAD DATASET
# ============================================

# Use your actual file name
df = pd.read_csv("your_file.csv")

# ============================================
# 2. CLEAN COLUMN NAMES
# ============================================

df.columns = (
    df.columns
    .str.strip()
    .str.replace(r'\s+', '_', regex=True)
    .str.replace(r'[^\w_]', '', regex=True)
)

print("Cleaned columns:")
print(df.columns.tolist())


# ============================================
# 3. REMOVE DUPLICATES
# ============================================

duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

df = df.drop_duplicates()


# ============================================
# 4. CLEAN NUMERICAL COLUMNS
# ============================================

# Age
df['Age'] = pd.to_numeric(
    df['Age'],
    errors='coerce'
)

# Annual Income
df['Annual_Income'] = (
    df['Annual_Income']
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True)
)

df['Annual_Income'] = pd.to_numeric(
    df['Annual_Income'],
    errors='coerce'
)

# Credit Score
df['credit_Score'] = pd.to_numeric(
    df['credit_Score'],
    errors='coerce'
)

# Loan Amount
df['Loan_Amount_INR'] = (
    df['Loan_Amount_INR']
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True)
)

df['Loan_Amount_INR'] = pd.to_numeric(
    df['Loan_Amount_INR'],
    errors='coerce'
)

# Monthly Visits
df['Monthly_Visits'] = df['Monthly_Visits'].replace({
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5
})

df['Monthly_Visits'] = pd.to_numeric(
    df['Monthly_Visits'],
    errors='coerce'
)


# ============================================
# 5. CLEAN DEBT TO INCOME
# ============================================

df['debt_to_income'] = (
    df['debt_to_income']
    .astype(str)
    .str.strip()
    .str.replace('%', '', regex=False)
    .str.replace('x', '', regex=False)
)

df['debt_to_income'] = pd.to_numeric(
    df['debt_to_income'],
    errors='coerce'
)

# Convert percentage values to decimal
df.loc[
    df['debt_to_income'] > 1,
    'debt_to_income'
] = df.loc[
    df['debt_to_income'] > 1,
    'debt_to_income'
] / 100


# ============================================
# 6. STANDARDIZE CATEGORICAL COLUMNS
# ============================================

# Employment Type
df['Employment-Type'] = (
    df['Employment-Type']
    .astype(str)
    .str.strip()
    .str.title()
)

# Education Level
df['Education_Level'] = (
    df['Education_Level']
    .astype(str)
    .str.strip()
    .str.title()
)

# City
df['city'] = (
    df['city']
    .astype(str)
    .str.strip()
    .str.lower()
)

df['city'] = df['city'].replace({
    'hyderbad': 'Hyderabad',
    'hyd': 'Hyderabad',
    'hyderabad': 'Hyderabad',
    'bangalore': 'Bengaluru',
    'bengaluru': 'Bengaluru'
})


# Customer Segment
df['customer_segment'] = (
    df['customer_segment']
    .astype(str)
    .str.strip()
    .str.title()
)


# Loan Type
df['loan_type'] = (
    df['loan_type']
    .astype(str)
    .str.strip()
    .str.lower()
)

df['loan_type'] = df['loan_type'].replace({
    'personal': 'Personal Loan',
    'personal loan': 'Personal Loan'
})


# Loan Approved
df['Loan_Approved'] = (
    df['Loan_Approved']
    .astype(str)
    .str.strip()
    .str.lower()
)

df['Loan_Approved'] = df['Loan_Approved'].replace({
    'yes': 'Yes',
    'y': 'Yes',
    '1': 'Yes',
    'no': 'No',
    'n': 'No',
    '0': 'No'
})


# ============================================
# 7. HANDLE INVALID VALUES
# ============================================

# Age must be between 0 and 100
df.loc[
    (df['Age'] < 0) | (df['Age'] > 100),
    'Age'
] = np.nan

# Credit Score must be between 300 and 850
df.loc[
    (df['credit_Score'] < 300) |
    (df['credit_Score'] > 850),
    'credit_Score'
] = np.nan

# Debt to Income must be between 0 and 1
df.loc[
    (df['debt_to_income'] < 0) |
    (df['debt_to_income'] > 1),
    'debt_to_income'
] = np.nan


# ============================================
# 8. HANDLE MISSING VALUES
# ============================================

numeric_columns = [
    'Age',
    'Annual_Income',
    'credit_Score',
    'Loan_Amount_INR',
    'Monthly_Visits',
    'debt_to_income'
]

# Fill numerical missing values with median
for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())


# Fill categorical missing values with mode
categorical_columns = [
    'Employment-Type',
    'Education_Level',
    'city',
    'customer_segment',
    'loan_type',
    'Loan_Approved'
]

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])


# ============================================
# 9. DETECT AND TREAT OUTLIERS
#    USING IQR METHOD
# ============================================

outlier_columns = [
    'Annual_Income',
    'Loan_Amount_INR'
]

for col in outlier_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Cap outliers instead of deleting rows
    df[col] = df[col].clip(
        lower=lower,
        upper=upper
    )


# ============================================
# 10. FIX FINAL DATA TYPES
# ============================================

df['Age'] = df['Age'].astype(int)

df['Annual_Income'] = df['Annual_Income'].astype(float)

df['credit_Score'] = df['credit_Score'].astype(int)

df['Loan_Amount_INR'] = df['Loan_Amount_INR'].astype(float)

df['Monthly_Visits'] = df['Monthly_Visits'].astype(int)

df['debt_to_income'] = df['debt_to_income'].astype(float)


# ============================================
# 11. FINAL ERROR CHECK
# ============================================

print("\n========== FINAL DATASET INFO ==========")

print("\nShape:")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nUnique categorical values:")

for col in categorical_columns:
    print("\n", col)
    print(df[col].unique())


# ============================================
# 12. CREATE FINAL CLEAN DATASET
# ============================================

df_cleaned = df.copy()

print("\n========== CLEANING COMPLETED ==========")
print(df_cleaned.head())

    CustomerID    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0       49184.0      2139          581        NaN       2
1         10002  65.0      162964.0      6197          732    6356.54       1
2         10003  56.0       26956.0     37281          503  143203.92       8
3         10004  55.0       92926.0       925          463  139627.88       5
4         10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target
0    France   Male        SME   Stay
1       USA   Male        SME  Churn
2    Canada   Male  Corporate   Stay
3       NaN   Male     Retail  Churn
4        UK  Other  Corporate  Churn

FileNotFoundError: [Errno 2] No such file or directory: 'your_file.csv'