In [2]:
import pandas as pd

df=pd.read_csv("C:\\Users\\Dell\\Downloads\\messy_customer_loan_dataset.csv")
df

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,477723.0,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,65.0,1394481.0,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,45.0,543340.0,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [ ]:
#Basic Cleaning

In [3]:
#1.Load the CSV file using Pandas and display the first 10 rows.
df.head(10)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
5,CUST100925,32.0,317590.0,690.0,Salaried,Graduate,M,Mumbai,Premium,Auto,235549.0,120,5.0,0.46,No
6,CUST100758,39.0,322966.0,707.0,Contract,Graduate,Married,Chennai,Mass,Personal,563319.0,24,7.0,0.323,No
7,CUST100793,54.0,999108.0,689.0,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783.0,48,NaN,0.233,Yes
8,CUST100965,65.0,478191.0,758.0,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872.0,72,5.0,0.375,No
9,CUST101198,67.0,1063307.0,774.0,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693.0,120,2.0,0.394,Yes

In [6]:
#2.Display the number of rows and columns in the dataset.

df.shape

(1535, 15)

In [7]:
#3.Display all column names and identify which column names have
#leading/trailing spaces.

# Display all column names
df.columns.tolist()

# Identify column names having leading/trailing spaces
for col in df.columns:
    if col != col.strip():
        print("Column with spaces:", repr(col))

Column with spaces: ' Customer ID '
Column with spaces: 'Age '
Column with spaces: 'credit Score '
Column with spaces: 'customer_segment '
Column with spaces: 'Monthly Visits '

In [8]:
#4.Clean all column names by removing extra spaces and converting them into a
#consistent format such as snake_case.

# Remove leading/trailing spaces and convert column names to snake_case

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns.tolist()

['customer_id',
 'age',
 'annual_income',
 'credit_score',
 'employment-type',
 'education__level',
 'marital_status',
 'city',
 'customer_segment',
 'loan_type',
 'loan_amount_(inr)',
 'tenure_months',
 'monthly_visits',
 'debt_to_income',
 'loan_approved?']

In [10]:
#5.Check the data type of every column.
df.dtypes

customer_id          object
age                  object
annual_income        object
credit_score         object
employment-type      object
education__level     object
marital_status       object
city                 object
customer_segment     object
loan_type            object
loan_amount_(inr)    object
tenure_months         int64
monthly_visits       object
debt_to_income       object
loan_approved?       object
dtype: object

In [11]:
#6.Find the total number of missing values in each column.

# Find missing values in each column
df.isnull().sum()

customer_id            0
age                   71
annual_income         84
credit_score          77
employment-type       60
education__level      46
marital_status         0
city                  52
customer_segment       0
loan_type              0
loan_amount_(inr)    102
tenure_months          0
monthly_visits        55
debt_to_income        89
loan_approved?         0
dtype: int64

In [13]:
#7.Find the percentage of missing values in each column.

df1=df.isnull().sum() / len(df) * 100
df1

customer_id          0.000000
age                  4.625407
annual_income        5.472313
credit_score         5.016287
employment-type      3.908795
education__level     2.996743
marital_status       0.000000
city                 3.387622
customer_segment     0.000000
loan_type            0.000000
loan_amount_(inr)    6.644951
tenure_months        0.000000
monthly_visits       3.583062
debt_to_income       5.798046
loan_approved?       0.000000
dtype: float64

In [19]:
#8.Find all rows where Age is missing.

#Find all rows where Age is missing
print(df[df['age'].isnull()])

     customer_id  age annual_income credit_score employment-type  \
21    CUST100354  NaN      302606.0        726.0             NaN
29    CUST100989  NaN    650000 INR        778.0   Self-Employed
100   CUST101150  NaN           100        723.0   Self-Employed
108   CUST100535  NaN      458878.0        782.0        Salaried
113   CUST101055  NaN     1112464.0          120        Salaried
...          ...  ...           ...          ...             ...
1424  CUST100392  NaN      570532.0        766.0        Contract
1430  CUST101368  NaN      519228.0        728.0        Business
1498  CUST100700  NaN      658802.0        772.0        Contract
1503  CUST100748  NaN      338339.0        673.0        Business
1516  CUST100770  NaN      708229.0        801.0        Business

     education__level marital_status       city customer_segment  loan_type  \
21           Graduate         Single  Bengaluru             Mass       Auto
29           Graduate       Divorced       Pune          unknown       Home
100              12th        Married        NaN             Mass  Education
108           Diploma        Married     Mumbai             Mass       Auto
113           Diploma        Married    Kolkata             Mass       Auto
...               ...            ...        ...              ...        ...
1424     Postgraduate        Married     Jaipur             Mass       Home
1430     Postgraduate        Married  Hyderabad             Mass       Home
1498     Postgraduate        Married     Mumbai             Mass       Auto
1503         Graduate        Married    Chennai          Premium   Business
1516              NaN         Single    Chennai          Premium   Personal

     loan_amount_(inr)  tenure_months monthly_visits debt_to_income  \
21            269320.0             84            6.0          0.353
29           1083921.0             48            5.0           0.4x
100           454937.0             48           five          0.303
108           549385.0             36            7.0          0.279
113           427759.0             84            3.0          0.102
...                ...            ...            ...            ...
1424          937612.0             36            3.0           0.51
1430          514679.0             12            4.0          0.392
1498          257699.0             24            4.0          0.584
1503          223704.0             12            7.0           0.02
1516          341664.0            120            5.0          0.651

     loan_approved?
21               No
29               No
100             Yes
108              No
113              No
...             ...
1424            Yes
1430            Yes
1498            Yes
1503             No
1516            Yes

[71 rows x 15 columns]

In [24]:
#9.Find all rows where Annual Income is missing.

# Find all rows where Annual Income is missing
print(df[df['annual_income'].isnull()])

     customer_id   age annual_income credit_score employment-type  \
41    CUST101081  64.0           NaN        749.0   Self-Employed
103   CUST101403  35.0           NaN        660.0   Self-Employed
119   CUST101095  36.0           NaN        782.0   self-employed
132   CUST101048  49.0           NaN        713.0        Salaried
144   CUST100530  64.0           NaN        761.0        Business
...          ...   ...           ...          ...             ...
1468  CUST100776  65.0           NaN        667.0   Self-Employed
1493  CUST101496  41.0           NaN        662.0   Self-Employed
1501  CUST100475  50.0           NaN        802.0        Contract
1532  CUST100861  66.0           NaN        686.0        Contract
1534  CUST101127  61.0           NaN        731.0        Salaried

     education__level marital_status       city customer_segment  loan_type  \
41            Diploma         Single    Kolkata          Premium   Personal
103          Graduate        Married      Delhi         Affluent       Home
119      Postgraduate        Married  Bengaluru         Affluent       Home
132      Postgraduate         Single  Bengaluru         Affluent      auto
144           Diploma         Single        NaN         Affluent   Business
...               ...            ...        ...              ...        ...
1468         GRADUATE         Single     Mumbai             Mass   Personal
1493             12th         Single    Kolkata         Affluent  Education
1501             12th       Divorced    Kolkata             Mass   Personal
1532            Other        Married      Delhi             Mass   Personal
1534     Postgraduate         Single    Chennai         Affluent  Education

     loan_amount_(inr)  tenure_months monthly_visits debt_to_income  \
41            254754.0             24            5.0          0.327
103                NaN             36            4.0          0.402
119           225725.0             60            5.0          0.341
132           301697.0             48            7.0           0.35
144          1182185.0            120            7.0           0.02
...                ...            ...            ...            ...
1468          995167.0             72            3.0            0.6
1493          693422.0             48            5.0          0.272
1501         1488587.0             36            5.0          0.023
1532          50000000             36            9.0          0.084
1534          753995.0             12            5.0          0.259

     loan_approved?
41               No
103              No
119             Yes
132             Yes
144             Yes
...             ...
1468            Yes
1493             No
1501            Yes
1532            Yes
1534             No

[84 rows x 15 columns]

In [26]:
#10.Remove completely duplicate rows and report how many duplicate rows were
#removed.

df = df.drop_duplicates()
df

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,477723.0,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,65.0,1394481.0,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,45.0,543340.0,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

In [28]:
#Data Type & Invalid Values

In [34]:
#11.The Age column contains numbers as well as values like "unknown" and
#"twenty five". Clean this column and convert it into a proper numeric column.

df['age'] = df['age'].replace({
    'unknown': pd.NA,
    'twenty five': 25
})

df['age'] = pd.to_numeric(df['age'], errors='coerce')

print(df['age'])

0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: age, Length: 1500, dtype: float64

In [37]:
#12.The Annual Income column contains values such as 650000 INR, ₹720000,
#1.2L, and N/A. Clean the column and convert the valid values into numeric
#format.

import numpy as np
import pandas as pd

def clean_income(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip().upper()

    # N/A or unknown values
    if value in ['N/A', 'NA', 'UNKNOWN', 'NONE', '']:
        return np.nan

    # Remove currency symbols and INR
    value = value.replace('₹', '').replace('INR', '').strip()

    # Values like 1.2L = 120000
    if value.endswith('L'):
        return float(value[:-1]) * 100000

    # Normal numeric values
    try:
        return float(value)
    except:
        return np.nan

df['annual_income'] = df['annual_income'].apply(clean_income)

df['annual_income']

0        297809.0
1       1048283.0
2       1043481.0
3        369591.0
4        666989.0
          ...
1530     477723.0
1531    1394481.0
1532          NaN
1533     543340.0
1534          NaN
Name: annual_income, Length: 1500, dtype: float64

In [47]:
#13.Clean the Credit Score column and identify values that cannot be converted
#into numbers.

#Clean Credit Score column
df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce')

# Identify values that cannot be converted
invalid_values = df[df['credit_score'].isna()]

print(invalid_values)

     customer_id   age  annual_income  credit_score employment-type  \
23    CUST100382  65.0       872829.0           NaN   Self-Employed
37    CUST100670  27.0       418793.0           NaN         Unknown
47    CUST100598  57.0       778581.0           NaN             NaN
73    CUST100362  62.0       604483.0           NaN   Self-Employed
84    CUST101115  30.0       858108.0           NaN        Contract
...          ...   ...            ...           ...             ...
1495  CUST100958  50.0       774288.0           NaN        Salaried
1499  CUST100511  67.0       499290.0           NaN        Contract
1502  CUST100857  32.0       659245.0           NaN        Business
1511  CUST101216  26.0      1403890.0           NaN             NaN
1529  CUST101096  24.0       520688.0           NaN        Contract

     education__level marital_status     city customer_segment  loan_type  \
23       Postgraduate        Married    Delhi             Mass   Personal
37           Graduate         Single   Jaipur             Mass   Business
47           Graduate        Married  Kolkata          unknown       Home
73               12th        Married     Pune         Affluent   Business
84               12th        Married   Jaipur             Mass       Auto
...               ...            ...      ...              ...        ...
1495         Graduate         Single  Kolkata             Mass   Personal
1499         Graduate        Married    Delhi          Premium   Business
1502              NaN        Married  Kolkata         Affluent  Education
1511         Graduate         Single     Pune             Mass       Home
1529     Postgraduate       Divorced    Delhi         Affluent       Auto

     loan_amount_(inr)  tenure_months monthly_visits debt_to_income  \
23            442006.0             72            3.0          0.234
37            400096.0            120            6.0          0.508
47            352976.0             84            6.0          0.361
73            382571.0             72            NaN          0.529
84            708169.0             72            5.0          0.723
...                ...            ...            ...            ...
1495          697241.0             72            4.0          0.323
1499          712165.0            120            7.0          0.423
1502          368435.0             60            2.0          0.097
1511          328004.0             72            6.0           0.05
1529          894941.0             60           five            NaN

     loan_approved?  credit_score_clean
23               No                 NaN
37               No                 NaN
47              Yes                 NaN
73              Yes                 NaN
84               No                 NaN
...             ...                 ...
1495             No                 NaN
1499            Yes                 NaN
1502              N                 NaN
1511       approved                 NaN
1529            Yes                 NaN

[96 rows x 16 columns]

In [49]:
#14.The Loan Amount column contains currency symbols, text, and numeric
#values. Remove the unwanted characters and convert it into numeric format.


# Remove unwanted characters and convert Loan Amount to numeric
df['loan_amount_(inr)'] = (
    df['loan_amount_(inr)']
    .astype(str)
    .str.replace(r'[₹$,]', '', regex=True)
    .str.strip()
)

df['loan_amount_(inr)'] = pd.to_numeric(df['loan_amount_(inr)'], errors='coerce')

print(df['loan_amount_(inr)'])

0         378342.0
1         751792.0
2         892792.0
3         908250.0
4         386370.0
           ...
1530     1106455.0
1531      222828.0
1532    50000000.0
1533      302389.0
1534      753995.0
Name: loan_amount_(inr), Length: 1500, dtype: float64

In [51]:
#15.The Monthly Visits column contains values such as "five", "N/A", and "-".
#Convert valid values into numeric values and handle invalid values.



# Convert Monthly Visits into numeric values
df['monthly_visits'] = pd.to_numeric(
    df['monthly_visits'].replace({
        'five': 5,
        'N/A': np.nan,
        '-': np.nan
    }),
    errors='coerce'
)

df['monthly_visits']

0        3.0
1       11.0
2        4.0
3       10.0
4        4.0
        ...
1530     NaN
1531     8.0
1532     9.0
1533     9.0
1534     5.0
Name: monthly_visits, Length: 1500, dtype: float64

In [54]:
#16.Clean the Debt to Income column where some values are written like 35%
#and 0.4x. Convert the valid values into a consistent numeric format.

def clean_dti(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()

    if value in ['unknown', 'n/a', 'na', '-']:
        return np.nan

    if value.endswith('%'):
        return float(value[:-1]) / 100

    if value.endswith('x'):
        return float(value[:-1])

    try:
        return float(value)
    except:
        return np.nan

df['debt_to_income'] = df['debt_to_income'].apply(clean_dti)

df['debt_to_income']

0       0.258
1       0.558
2         NaN
3       0.356
4       0.169
        ...
1530    0.569
1531    0.344
1532    0.084
1533    0.089
1534    0.259
Name: debt_to_income, Length: 1500, dtype: float64

In [55]:
#17.After cleaning the numerical columns, check which columns are still stored as
#object data type.

#Check columns that are still object datatype
df.select_dtypes(include='object').columns

Index(['customer_id', 'employment-type', 'education__level', 'marital_status',
       'city', 'customer_segment', 'loan_type', 'loan_approved?'],
      dtype='object')

In [ ]:
#Categorical Cleaning

In [57]:
#18.Find all unique values in the Employment-Type column.

df['employment-type'].unique()

array(['Self-Employed', 'Contract', 'Salaried', ' SALARIED ',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

In [60]:
#19.Standardize the Employment-Type column so that values such as salaried,
#SALARIED, and Salaried become one consistent value.

df['employment-type'] = (
    df['employment-type']
    .str.strip()
    .str.lower()
    .replace({
        'self employed': 'self-employed',
        'unknown': np.nan
    })
)

df['employment-type'].unique()

array(['self-employed', 'contract', 'salaried', 'business', nan],
      dtype=object)

In [65]:
#20.Clean the Education Level column and make values such as graduate,
#GRADUATE, and Graduate consistent.


df['education__level'] = (
    df['education__level']
    .str.strip()
    .str.lower()
)

df['education__level'].unique()

array(['12th', 'graduate', 'postgraduate', 'diploma', nan, 'other'],
      dtype=object)

In [67]:
#21.Clean the City column. Identify incorrect or inconsistent values such as
#hyderbad, Hyd, Bangalore, and Bengaluru.

#Clean City column

df['city'] = (
    df['city']
    .str.strip()
    .str.lower()
    .replace({
        'hyderbad': 'hyderabad',
        'hyd': 'hyderabad',
        'bangalore': 'bengaluru'
    })
)

df['city'].unique()

array(['mumbai', 'jaipur', 'kolkata', 'hyderabad', 'chennai', 'bengaluru',
       nan, 'delhi', 'pune'], dtype=object)

In [70]:
#22.Find all unique values in the Customer Segment column and identify invalid
#categories.

#Find unique values in Customer Segment
df['customer_segment'].unique()


# Identify invalid categories
valid_segments = ['retail', 'sme', 'corporate', 'premium']

invalid_segments = df[
    ~df['customer_segment'].str.strip().str.lower().isin(valid_segments)
    & df['customer_segment'].notna()
]

invalid_segments['customer_segment'].unique()

array(['Mass', 'Affluent', 'unknown', 'High Value', 'mass'], dtype=object)

In [71]:
#23.Clean the Loan Type column so that values such as personal, PERSONAL,
#and personal loan are standardized.

#Clean Loan Type column
df['loan_type'] = (
    df['loan_type']
    .str.strip()
    .str.lower()
    .replace({
        'personal loan': 'personal'
    })
)

df['loan_type'].unique()

array(['education', 'auto', 'home', 'personal', 'business', 'home loan',
       'unknown'], dtype=object)

In [72]:
#24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No,
#NO, N, and 0. Convert them into only Yes/No.

#Clean Loan Approved column
df['loan_approved?'] = (
    df['loan_approved?']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'yes': 'Yes',
        'y': 'Yes',
        '1': 'Yes',
        'no': 'No',
        'n': 'No',
        '0': 'No',
        'nan': np.nan
    })
)

df['loan_approved?'].unique()

array(['No', 'Yes', 'pending', 'approved'], dtype=object)

In [ ]:
#Outliers & Data Validation

In [73]:
#25.Check the Age column and identify unrealistic ages such as negative ages or
#ages above 100.


#Identify unrealistic ages

invalid_age = df[
    (df['age'] < 0) | (df['age'] > 100)
]

invalid_age[['age']]

        age
143   105.0
264   105.0
308   105.0
383    -3.0
581   130.0
689    -3.0
892    -3.0
923   105.0
1039   -3.0
1070   -3.0
1399  105.0
1465  105.0

In [74]:
#26.Check the Credit Score column and identify values outside the valid credit-
#score range.

#Identify invalid Credit Score values
invalid_credit_score = df[
    (df['credit_score'] < 300) | (df['credit_score'] > 850)
]

invalid_credit_score[['credit_score']]

      credit_score
1            874.0
57           852.0
83           856.0
97           905.0
113          120.0
123          999.0
178          854.0
295          250.0
296            0.0
327          856.0
342          120.0
361          858.0
369          889.0
399          863.0
542          120.0
680          120.0
690          860.0
710            0.0
726          903.0
807          120.0
830          870.0
867          872.0
923          878.0
927          250.0
930            0.0
959            0.0
964          120.0
992          867.0
1003         868.0
1068         878.0
1082           0.0
1096         865.0
1114         870.0
1132         861.0
1133         887.0
1151         863.0
1159         250.0
1217         250.0
1232         250.0
1239         876.0
1284         851.0
1286         120.0
1288           0.0
1352         250.0
1407         854.0
1461         120.0
1531           0.0

In [75]:
#27.Detect outliers in Annual Income using the IQR method.

#Detect outliers in Annual Income using IQR

Q1 = df['annual_income'].quantile(0.25)
Q3 = df['annual_income'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df['annual_income'] < lower_limit) |
    (df['annual_income'] > upper_limit)
]

print(outliers[['annual_income']])
print("Number of outliers:", len(outliers))

      annual_income
14        1548824.0
61        1777657.0
74        1907548.0
180       1483255.0
184       1895511.0
...             ...
1409      1521141.0
1464      1996474.0
1466      1604257.0
1467      1531271.0
1515     80000000.0

[67 rows x 1 columns]
Number of outliers: 67

In [84]:
#28.Detect outliers in Loan Amount using the IQR method.

#Detect outliers in Loan Amount using IQR
Q1 = df['loan_amount_(inr)'].quantile(0.25)
Q3 = df['loan_amount_(inr)'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df['loan_amount_(inr)'] < lower_limit) |
    (df['loan_amount_(inr)'] > upper_limit)
]

outliers[['loan_amount_(inr)']]
len(outliers)

81

In [86]:
#29.Check the Debt to Income column and identify impossible values such as
#negative values or values greater than 1.


#Identify impossible Debt to Income values
invalid_dti = df[
    (df['debt_to_income'] < 0) |
    (df['debt_to_income'] > 1)
]

invalid_dti[['debt_to_income']]

      debt_to_income
31              -0.2
39               1.2
77               9.0
115              3.5
278              3.5
486              3.5
573              1.2
796              3.5
941              9.0
1048             1.2
1107             1.2
1177             9.0
1296             9.0
1353             1.2
1390             9.0
1425            -0.2
1463            -0.2
1524             3.5

In [88]:
#30.Final cleaning task: Create a completely cleaned version of the dataset by:
#• Cleaning column names
#• Removing duplicates
#• Handling missing values
#• Fixing data types
#• Cleaning numerical columns
#• Standardizing categorical values
#• Handling invalid values
#• Detecting and treating outliers
#• Checking the final dataset for remaining errors


#FINAL DATA CLEANING

#Clean column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

# Remove completely duplicate rows
df = df.drop_duplicates()

# Remove duplicate Customer IDs
df = df.drop_duplicates(subset='customer_id')

# Clean numerical columns
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['annual_income'] = pd.to_numeric(df['annual_income'], errors='coerce')
df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce')
df['loan_amount_(inr)'] = pd.to_numeric(df['loan_amount_(inr)'], errors='coerce')
df['tenure_months'] = pd.to_numeric(df['tenure_months'], errors='coerce')
df['monthly_visits'] = pd.to_numeric(df['monthly_visits'], errors='coerce')
df['debt_to_income'] = pd.to_numeric(df['debt_to_income'], errors='coerce')

# Handle invalid Age
df.loc[(df['age'] < 0) | (df['age'] > 100), 'age'] = np.nan

# Handle invalid Credit Score
df.loc[
    (df['credit_score'] < 300) | (df['credit_score'] > 850),
    'credit_score'
] = np.nan

# Handle invalid Debt to Income
df.loc[
    (df['debt_to_income'] < 0) | (df['debt_to_income'] > 1),
    'debt_to_income'
] = np.nan

# Standardize Employment Type
df['employment-type'] = (
    df['employment-type']
    .str.strip()
    .str.lower()
    .replace({
        'self employed': 'self-employed',
        'unknown': np.nan
    })
)

#Standardize Education Level
df['education__level'] = (
    df['education__level']
    .str.strip()
    .str.lower()
    .replace({
        'post graduate': 'postgraduate'
    })
)

#Standardize City
df['city'] = (
    df['city']
    .str.strip()
    .str.lower()
    .replace({
        'hyderbad': 'hyderabad',
        'hyd': 'hyderabad',
        'bangalore': 'bengaluru'
    })
)

# 11. Standardize Loan Type
df['loan_type'] = (
    df['loan_type']
    .str.strip()
    .str.lower()
    .replace({
        'personal loan': 'personal'
    })
)

# 12. Standardize Loan Approved
df['loan_approved?'] = (
    df['loan_approved?']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'yes': 'Yes',
        'y': 'Yes',
        '1': 'Yes',
        'no': 'No',
        'n': 'No',
        '0': 'No',
        'nan': np.nan
    })
)

# Treat Annual Income outliers using IQR
Q1 = df['annual_income'].quantile(0.25)
Q3 = df['annual_income'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df.loc[
    (df['annual_income'] < lower) |
    (df['annual_income'] > upper),
    'annual_income'
] = np.nan

#Treat Loan Amount outliers using IQR
Q1 = df['loan_amount_(inr)'].quantile(0.25)
Q3 = df['loan_amount_(inr)'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df.loc[
    (df['loan_amount_(inr)'] < lower) |
    (df['loan_amount_(inr)'] > upper),
    'loan_amount_(inr)'
] = np.nan

#Fill missing numerical values with median
numeric_columns = [
    'age',
    'annual_income',
    'credit_score',
    'loan_amount_(inr)',
    'tenure_months',
    'monthly_visits',
    'debt_to_income'
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

#Fill missing categorical values with mode
categorical_columns = [
    'employment-type',
    'education__level',
    'marital_status',
    'city',
    'customer_segment',
    'loan_type',
    'loan_approved?'
]

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

#Final data-quality checks
df.isna().sum()
df.duplicated().sum()
df['customer_id'].duplicated().sum()
df.dtypes
df.shape
df.head()

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,credit_score_clean
0,CUST101160,37.0,297809.0,698.0,self-employed,12th,Married,mumbai,Mass,education,378342.0,60,3.0,0.2580,No,698.0
1,CUST100077,36.0,1048283.0,716.0,contract,graduate,Single,jaipur,PREMIUM,auto,751792.0,48,11.0,0.5580,Yes,874.0
2,CUST100317,55.0,1043481.0,661.0,self-employed,postgraduate,Married,kolkata,Affluent,auto,892792.0,84,4.0,0.3435,Yes,661.0
3,CUST101041,54.0,369591.0,722.0,salaried,graduate,Single,kolkata,Premium,home,908250.0,84,10.0,0.3560,Yes,722.0
4,CUST101358,27.0,666989.0,727.0,self-employed,graduate,Married,hyderabad,Mass,education,386370.0,72,4.0,0.1690,Yes,727.0